import shlex
import os, sys, json, subprocess
from dataclasses import dataclass
from typing import TypeAlias, TextIO
from enum import Enum

KB = 1024
MB = 1024 * 1024




class MessageType(Enum):
    INIT     = 1
    INITD    = 2
    DIDOPEN  = 3
    DIDCLOSE = 4

MT: type = MessageType

class URIType(Enum):
    LOCAL_PROJECT      = 1,
    REMOTE_PROJECT     = 2,
    REMOTE_HEADER      = 3


# Kind of a random place to put this, and also this value should not be hardcoded in the first place.  Hopefully I will remember
# to do something about this.
# TODO: Un-hardcode this value so that this project doesn't only work for my specific setup
development_team = '6DDGC468AY'
headers_dir_name = 'remote-header-files'

user_home_local = os.path.expanduser('~')
# rdt_root_path = f'{user_home_local}\\.remote-development-tools'
rdt_root_path = os.path.expanduser('~/.remote-development-tools').replace('\\', '/')
lsp_proxy_config_path = os.path.join(rdt_root_path, 'lsp-proxy-config.json').replace('\\', '/')

with open(os.path.expanduser(lsp_proxy_config_path), 'r') as f:
    config_dct: dict = json.load(f)

logging_enabled = config_dct.get('logging_enabled', False)
logfile_path = os.path.expanduser('~/tmp/lsp_proxy_log.txt').replace('\\', '/') if logging_enabled else os.devnull
logfile = open(logfile_path, 'ab')
# logfile_error_path = 'C:/Users/sjber/tmp/lsp_proxy_error_log.txt'
logfile_error_path = os.path.expanduser('~/tmp/lsp_proxy_error_log.txt') if logging_enabled else os.devnull
logfile_errors = open(logfile_error_path, 'wb')

remote_host: str = config_dct.get('remote_host', '')
user_home_remote: str = config_dct.get('remote_user_home', '')
remote_coding_root: str = config_dct.get('remote_coding_root', '')
local_coding_root: str = config_dct.get('local_coding_root', '')

if not all([remote_host, remote_coding_root, local_coding_root, user_home_remote]):
    raise RuntimeError(f'Error, not all required config entries found: remote_host, remote_coding_root, local_coding_root, user_home_remote')




# Keep track of currently used message ids, because occasionally we need to genuinely create a new message from scratch.
# So this is to help ensure no id collisions occur in that scenario.  It is declared here just so it is available in all modules
currently_used_ids = set()

# Used to keep track of how many textDocument/documentSymbol requests have been MANUALLY sent (i.e. generated by this proxy, not by nvim)
# It is used to create custom string ids in get_available_documentsymbol_id, to avoid id collisions with messages generated by nvim itself
document_symbol_request_count = 0

#messages cached by id.  id can be str|int
cached_messages = {}

def get_available_documentsymbol_id() -> str:
    global document_symbol_request_count
    id = f'proxy/documentSymbol/{document_symbol_request_count}'
    document_symbol_request_count += 1
    return id


def log(data, suppress_huge_messages=True, max_message_size=20*MB) -> None:
    if logging_enabled:
        if type(data) == str:
            data = data.encode(errors='replace')
        if not suppress_huge_messages or (len(data) < max_message_size):
            logfile.write(data)
            logfile.flush()

def log_unmissable(data, suppress_huge_messages=True, max_message_size=20*MB) -> None:
    if logging_enabled:
        max_message_size /= 50
        if type(data) == str:
            data = data.encode(errors='replace')

        if not suppress_huge_messages or (len(data) < max_message_size):
            for _ in range(50):
                logfile.write(data + b'\n')
            logfile.flush()

def log_raise_error(err_msg: str|bytes, unmissable=True) -> None:
    if type(err_msg) == bytes:
        err_msg = err_msg.decode(errors='replace')
    if unmissable:
        log_unmissable(err_msg)
    raise RuntimeError(err_msg)

def ensure_drive_letter(path: str, drive_letter='C') -> str:
    drive_prefix = drive_letter + ':'
    if path.startswith(drive_prefix):
        return path
    path = path if (path.startswith('/') or path.startswith('\\')) else '/' + path
    return drive_prefix + path

def normalize_path(path: str, sep='/', strip_drive=False) -> str:
    if isinstance(path, int):
        log_unmissable(f'NORMALIZE_PATH RECEIEVED INT: {str(path)}')
    if strip_drive:
        path = os.path.splitdrive(path)[1]
    if sep == '/':
        return path.replace('\\', '/')
    elif sep == '\\':
        return path.replace('/', '\\')
    raise RuntimeError(f"Invalid separator, must be '/' or '\\'.  Offending path: {path}")

def path_depth(path: str):
    return len([part for part in normalize_path(path).split('/') if part])

def get_project_root_path(path: str = '') -> str:
    if not path:
        path = os.getcwd()

    curr_path = path
    # os.listdir(curr_path)

    while not '.git' in os.listdir(curr_path) and (path_depth(curr_path) > 0):
        curr_path = os.path.split(curr_path)[0]
    return curr_path

current_project_root_local = get_project_root_path()
for arg in sys.argv[1:]:
    if arg.startswith('--project-root'):
        current_project_root_local = arg.split('=')[1]
        break
log_unmissable(f'CURRENT_PROJECT_ROOT_LOCAL: {current_project_root_local}')
headers_dir_path = normalize_path(os.path.join(current_project_root_local, headers_dir_name))


def is_windows_path(path: str) -> bool:
    return len(os.path.splitdrive(path)[0]) > 0

def is_windows_uri(uri: str) -> bool:
    if not uri.startswith('file:///'):
        log_raise_error(f'ERROR, invalid uri passed to function is_windows_uri: {uri}')
    path = uri[8:]
    return len(os.path.splitdrive(path)[0]) > 0

def path_to_uri(path: str):
    normed_path = normalize_path(path)
    if is_windows_path(normed_path):
        return f'file:///{normalize_path(normed_path)}'
    return f'file://{normed_path}'

def uri_to_path(uri: str):
    idx = 8 if is_windows_uri(uri) else 7
    return uri[idx:]

def path_unix_to_windows(path: str, drive_letter='C') -> str:
    if path.startswith('/'):
        return f'{drive_letter}:{normalize_path(path, '\\')}'
    return normalize_path(path, '\\')

def path_windows_to_unix(path: str):
    return normalize_path(path, strip_drive=True)


def get_path_separator(path: str):
    fslash_num_segments = len(path.split('/'))
    bslash_num_segments = len(path.split('\\'))
    if bslash_num_segments > fslash_num_segments:
        return '\\'
    return '/'

def path_has_drive_letter(path: str):
    sep = get_path_separator(path)
    first_segment = path.split(sep)[0]
    if len(first_segment) == 2:
        return first_segment[0].isalpha() and (first_segment[1] == ':')
    return False

def uri_has_drive_letter(uri: str):
    return path_has_drive_letter(uri_to_path(uri))



def uri_unix_to_windows(uri: str) -> str:
    if not uri.startswith('file:///'):
        log_raise_error(f'ERROR, invalid uri passed to function is_windows_uri: {uri}')
    path = normalize_path(uri[7:], '/')
    normed_windows_path = normalize_path(path_unix_to_windows(path))
    return f'file:///{normed_windows_path}'

def uri_windows_to_unix(uri: str) -> str:
    if not uri.startswith('file:///'):
        log_raise_error(f'ERROR, invalid uri passed to function is_windows_uri: {uri}')
    path = uri[8:]
    unix_path = path_windows_to_unix(path)
    return f'file://{unix_path}'

def bfs_dict(dct: dict, key):
    '''Performs a breadth first search in `dct` for `key`, returning the first result found, otherwise None.
       Automatically handles both dicts and lists as subitems, but `dct` itself must be a dict.
    '''
    for k, val in dct.items():
        if k == key:
            return val
        if isinstance(val, dict):
            res = bfs_dict(val, key)
            if res:
                return res
        elif isinstance(val, list):
            for entry in val:
                if isinstance(entry, dict):
                    res = bfs_dict(entry, key)
                    if res:
                        return res





# Checks if path is inside of dir
def is_subdir(path: str, dir: str):
    '''
    `path`: The path to test if it is inside of `dir`
    `dir` : The directory to test if `path` is inside of
    Returns True if `path` is recursively inside of `dir`, otherwise return False
    '''
    if not dir:
        return False
    path_normed = normalize_path(path, strip_drive=True)
    dir = normalize_path(dir, strip_drive=True)
    return path_normed.startswith(dir)



def is_project_path(path: str):
    '''
    Returns True if `path` is inside of `current_project_root_local`, i.e. the current project root path.  Otherwise returns False.
    '''
    local_coding_root_normed = normalize_path(local_coding_root, strip_drive=True)
    remote_coding_root_normed = normalize_path(remote_coding_root, strip_drive=True)
    path_normed = normalize_path(path, strip_drive=True)
    return path_normed.startswith(local_coding_root_normed) or path_normed.startswith(remote_coding_root_normed)
    # return is_subdir(path, current_project_root_local)



def dfs(obj: list|dict, x):
    for key in obj:
        val = key if type(obj) == list else obj[key]
        if x == key:
            return val
        if type(val) not in [dict, list]:
            continue
        res = dfs(val, x)
        if res is not None:
            return res

def dfs_path(obj: list|dict, x, path:list=[]):
    for i, key in enumerate(obj):
        val = key if type(obj) == list else obj[key]
        if x == key:
            return path + [key if type(obj)==dict else i]
        if type(val) not in [dict, list]:
            continue
        res = dfs_path(val, x, path + [key if type(obj)==dict else i])
        if res is not None:
            return path + [key if type(obj)==dict else i]

def parse_content_length_from_bytes(data: bytes) -> int:
    log(data)
    for bline in data.splitlines():
        if bline.startswith(b'Content-Length'):
            cl_bstr = bline.split(b':')[1].strip()
            return int(cl_bstr)
    raise RuntimeError('Failed to find Content-Length')


CL_BSTR = b'Content-Length: '
CL_STR = 'Content-Length: '
INVALID_ID = 0


def get_body_start_idx(data: bytes) -> int:
    if not data.startswith(CL_BSTR):
        raise ValueError(f"Error, message bytes does not start with 'Content-Length: '")
    return data.find(b'\r\n\r\n', len(CL_BSTR)) + 4


#Handles buffering issues and reads a full LSP message from file_descriptor fd
def read_full_message(fd: int) -> tuple[bytes, int]:
    data = b'' #buff
    while not CL_BSTR in data:
        data += os.read(fd, 1)
    while not data.endswith(b'\r\n\r\n'):
        data += os.read(fd, 1)

    content_length = parse_content_length_from_bytes(data)
    data += os.read(fd, content_length)
    body_start_idx = get_body_start_idx(data)

    # log(f'read {len(data)} bytes, and found a content-length of: {content_length}, for a total of {bytes_remaining} bytes remaining\n\n')
    while len(data) - body_start_idx < content_length:
        bytes_to_read = content_length - (len(data) - body_start_idx)
        data += os.read(fd, bytes_to_read)
    return data, body_start_idx



# def run_process(cmd: str|list[str]) -> subprocess.CompletedProcess:
#     if isinstance(cmd, str):
#         cmd = shlex.split(cmd)
#     proc = subprocess.run(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#     if proc.returncode:
#         raise RuntimeError(f"Error while running command: {shlex.join(cmd)}\n\tError message: {proc.stderr.decode(errors='replace')}")
#     return proc



user_home_local_normed = normalize_path(user_home_local, strip_drive=True)
# rdt_root_path = f'{user_home_local}\\.remote-development-tools'
# rdt_root_path = normalize_path(os.path.expanduser('~/.remote-development-tools'))
# rdt_config_filename = 'config.json'
# rdt_config_path = normalize_path(os.path.join(rdt_root_path, rdt_config_filename))
rdt_state_name = 'lsp-proxy-state.json'
rdt_state_path = os.path.join(rdt_root_path, rdt_state_name)
def __clangd_should_exclude(arg: str):
    to_exclude = ['--remotehost', '--root', '--project-root']
    for exclusion in to_exclude:
        if arg.startswith(exclusion):
            return True
    return False
clangd_args = [arg for arg in sys.argv[1:] if not __clangd_should_exclude(arg)]
nvim_data_path = os.path.join(user_home_local, 'AppData', 'Local', 'nvim-data')


# with open(rdt_config_path, 'r') as f:
#     config: dict = json.load(f)
# user_home_remote = config.get('user_home_remote', '')
# local_coding_root  = normalize_path(os.path.join(user_home_local, 'Coding'))
# if local_coding_root.startswith('/'):
#     local_coding_root = 'C:' + local_coding_root
# remote_coding_root = normalize_path(os.path.join(user_home_remote, 'Codingstuff'))
local_coding_root_normed = os.path.splitdrive(local_coding_root)[1]
definition_mappings_path = normalize_path(os.path.join(rdt_root_path, 'definition-mappings.json'))



def is_uri(s: str):
    '''Checks whether `s` is a uri or not.  i.e. does it start with file:///'''
    return s.replace('\\/', '/').startswith('file:///')


# Path/URI tranlsation directions
LOCAL_TO_REMOTE = 0
REMOTE_TO_LOCAL = 1


#Generate clangd path mapping for `local_path` (where local_path is a windows path)
def clangd_path_mapping_path(local_path: str, direction=LOCAL_TO_REMOTE) -> str:
    if not local_path:
        return ''
    if direction == LOCAL_TO_REMOTE:
        headers_dir_path_normed = normalize_path(headers_dir_path, strip_drive=True)
        return normalize_path(local_path, strip_drive=True).replace(local_coding_root_normed, remote_coding_root)
    elif direction == REMOTE_TO_LOCAL:
        remote_coding_root_normed = normalize_path(remote_coding_root, strip_drive=True)
        return ensure_drive_letter(normalize_path(local_path, strip_drive=True).replace(remote_coding_root_normed, local_coding_root_normed))
    else:
        raise RuntimeError(f'Error, invalid mapping direction.  Must be `LOCAL_TO_REMOTE` or `REMOTE_TO_LOCAL`')

current_project_root_remote = clangd_path_mapping_path(current_project_root_local)

def is_symbol_separator(s: str):
    '''Returns True if `s` is a character which acts as a symbol/token separator'''
    nonspace_separators = ['(', ')', '[', ']', '{', '}', '|', '.', ',', ':']
    return s.isspace() or s in nonspace_separators

def get_symbol_at_uri(uri: str, row: int, col: int, one_indexed=False) -> str:
    '''
    Gets the full token/symbol at (row, col) in the file located at uri.
    If one_indexed is True, then 1 is subtracted from both row and col.  nvim passes rows (line) and cols (character) as 1-indexed,
    so one_indexed is True by default.
    '''
    if one_indexed:
        row -= 1
        col -= 1

    path = uri_to_path(uri)
    if not os.path.exists(path):
        raise RuntimeError(f'Error, file at supplied uri not found.  uri: {uri}')

    # I genuinely didnt know you could do this until very recently, but you CAN enumerate directly over a file object.
    # And it is actually more memory efficient, because doing it this way (versus the equivalent thing with .readlines())
    # only loads 1 line at a time into memory, versus loading the whole file with .readlines()

    with open(path, 'r') as f:
        for i, line in enumerate(f):
            if i == row:
                if len(line) < col:
                    return ''
                start = col
                end = col
                while start >= 0 and not is_symbol_separator(line[start]):
                    log(f'start: {start}\n')
                    start -= 1
                while end < len(line) and not is_symbol_separator(line[end]):
                    end += 1

                # add 1 to start because we went back until we found a space
                # we dont need to subtract 1 from end because of how slicing works, i.e. the ending space automatically won't be included
                start += 1
                return line[start:end]
    return ''








#generate clangd uri mapping for `local_uri` (where local_uri is a windows uri)
# def clangd_path_mapping_uri(local_uri: str, direction=LOCAL_TO_REMOTE):
#     if not local_uri:
#         return ''
#     dirs = ['LOCAL_TO_REMOTE', 'REMOTE_TO_LOCAL']
#     log(f'RUNNING CLANGD_PATH_MAPPING_URI ON WITH DIRECTION: {dirs[direction]} ON URI: {local_uri}')
#     local_path = local_uri.replace('file://', '')
#     if not os.path.exists(local_path) and local_path.startswith('/'):
#         local_path = local_path[1:]
#     mapped_path = clangd_path_mapping_path(local_path, direction)
#     uri_prefix = 'file://'
#     if direction == REMOTE_TO_LOCAL:
#         uri_prefix += '/'
#     mapped_uri = uri_prefix + mapped_path
#     if not mapped_uri.startswith('file:///'):
#         mapped_uri = mapped_uri.replace('file://', 'file:///')
#     return mapped_uri

def clangd_path_mapping_uri(uri: str, direction: int = LOCAL_TO_REMOTE):
    #Drive letter is handled by clangd_path_mapping_path, so it does not need to be handled explicitly here
    if not uri:
        return ''
    path = uri_to_path(uri)
    mapped_path = clangd_path_mapping_path(path, direction)
    return path_to_uri(mapped_path)

def translate_paths_recursively_for_remote(dct: dict, direction=LOCAL_TO_REMOTE):
    '''
    Translates all paths and uris in a dict
    '''
    path_keys_to_translate = ['rootPath', 'path', 'oldPath', 'newPath']
    uri_keys_to_translate = ['rootUri', 'uri', 'targetUri', 'oldUri', 'newUri']
    for key, val in dct.items():
        if key in path_keys_to_translate:
            dct[key] = clangd_path_mapping_path(val, direction)
        elif key in uri_keys_to_translate:
            dct[key] = clangd_path_mapping_uri(val, direction)
        elif isinstance(val, str):
            if is_uri(val):
                # There can be URIs under unexpected keys.  This elif block is to catch those instances and make sure they are translated
                dct[key] = clangd_path_mapping_uri(val, direction)
            elif os.path.exists(val):
                # we know val is a str here, so it is safe to make this check.  If it is true, then of course val is a path,
                # and so should be translated
                dct[key] = clangd_path_mapping_path(val, direction)
        elif isinstance(val, dict):
            # Any time val is a dict, we recursively call this function on it
            dct[key] = translate_paths_recursively_for_remote(val, direction)
            # if the key is workspaceFolders, then manually remap 'name' parameter to be the root folder name
        elif isinstance(val, list):
            if key == 'result':
                for res in val:
                    if 'uri' in res:
                        # log_unmissable('FOUND `uri` IN OBJECT)
                        uri = res['uri']
                        res['uri'] = clangd_path_mapping_uri(uri, direction)
            elif key == 'workspaceFolders':
                folders_lst = []
                for folder in val:
                    uri = folder.get('uri', '')
                    if uri:
                        original_name_path = uri_to_path(uri)
                        if is_windows_path(original_name_path):
                            path = clangd_path_mapping_path(original_name_path)
                            log_unmissable(f'CHANGING WORKSPACE FOLDERS NAME TO: {path}')
                            folder['name'] = path
                            folder['uri'] = clangd_path_mapping_uri(uri)
                    folders_lst.append(folder)
                dct[key] = folders_lst


                pass


        # else:
        #     #handle the weird cases
        #     if os.path.exists(val):
        #         #this proves `val` is a path of course, and a local one, so it should be translated
        #         dct[key] = clangd_path_mapping_path(val, direction)

    return dct








def get_proxy_state() -> dict:
    with open(rdt_state_path, 'r') as f:
        proxy_state: dict = json.load(f)
    return proxy_state


def set_proxy_state(curr_proxy_state: dict) -> None:
    log('In actual set_proxy_state function')
    with open(rdt_state_path, 'w') as f:
        new_contents = json.dumps(curr_proxy_state)
        f.write(new_contents)
        # f.flush()

def clear_proxy_state(proxy_state: dict = {}) -> None:
    proxy_state['active_projects'] = []
    proxy_state['active_proxies'] = []
    log('Setting proxy state to: ' + '{\'active_projects\': []}')
    set_proxy_state({'active_projects': []})
    log('Finished setting proxy state')


def project_is_active(project, proxy_state: dict|None = None):
    if proxy_state is None:
        proxy_state = get_proxy_state()
    active_projects = proxy_state['active_projects']
    log_unmissable(f'project: {project}')
    proj_root = project if isinstance(project, str) else project['rootPath']
    for proj in active_projects:
        if proj['rootPath'] == proj_root:
            return True
    return False

def get_available_id(proxy_state: dict, key: str):
    lst = proxy_state[key]
    for i in range(1000):
        i_found = False
        for entry in lst:
            if entry['id'] == i:
                i_found = True
                break
        if not i_found:
            return i
    raise RuntimeError(f'Error, unable to find available id in the range 0-1000')


def add_active_project(project: dict, proxy_state: dict|None = None):
    if not proxy_state:
        proxy_state = get_proxy_state()
    active_projects = proxy_state.get('active_projects', [])
    if isinstance(project, str):
        project = {'rootPath': project, id: get_available_id(proxy_state, 'active_projects')}
    if not project_is_active(project, proxy_state):
        proxy_state['active_projects'].append(project)
    set_proxy_state(proxy_state)



def get_key_value_from_message_dct(dct: dict, key: str, message_type: MessageType = MT.INIT):
    '''
    Gets a value from a dict, which is the result of json loading a LSP message.
    '''

    base_keys = ['id', 'params', 'method', 'jsonrpc']
    params_keys = ['workspaceFolders', 'processId', 'rootPath', 'rootUri', 'clientInfo', 'workDoneToken']

    if key in base_keys:
        return dct[key]
    elif key in params_keys:
        return dct['params'][key]
    raise RuntimeError('Error, key not found in dict base or `params`')


def find_file_by_name(name: str, search_root=''):
    if not search_root:
        search_root = os.getcwd()
    for dirpath, dirnames, filenames in os.walk(search_root):
        for fname in filenames:
            if fname == name:
                return normalize_path(os.path.join(dirpath, fname))


def find_clangd_exe(additional_search_roots: list[str] = [], error_on_failure=True) -> str:
    mason_root = os.path.join(nvim_data_path, 'mason')
    mingw64_root = os.path.join('C:/msys64', 'mingw64') 
    mingw32_root = os.path.join('C:/msys64', 'mingw64') 
    appdata_local_root = os.path.join(user_home_local, 'AppData', 'Local')
    search_roots = [mason_root, mingw64_root, mingw32_root, appdata_local_root] + additional_search_roots

    for search_root in search_roots:
        clangd_path = find_file_by_name('clangd.exe', search_root)
        if clangd_path:
            return clangd_path
    if error_on_failure:
        raise RuntimeError('Error, unable to find clangd.exe in any search root')
    return ''



def update_config(remote_host='', user_home_remote='', clangd_path=''):
    '''
    Updates the config file for RemoteDevelopmentTools (located at ~/.remote-development-tools/config.json)
    If no arguments are passed, the current `config` dict is saved to the file as a JSON object.
    Otherwise any arguments (as kwargs key-value pairs) are used to update the config variable, and then it is saved.
    '''
    global config_dct

    if remote_host:
        config_dct['remote_host'] = remote_host
    if user_home_remote:
        config_dct['user_home_remote'] = user_home_remote
    if clangd_path:
        config_dct['clangd_exe'] = clangd_path

    with open(lsp_proxy_config_path, 'w') as f:
        json.dump(config_dct, f)



def close_resources():
    if not logfile.closed:
        logfile.close()
    if not logfile_errors.closed:
        logfile_errors.close()



def run_process(args: str|list[str]) -> str:
    if isinstance(args, str):
        args = shlex.split(args)
    proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if proc.returncode != 0:
        print(f'Error executing command: {args}\nError text:')
        print(proc.stderr.decode(errors='replace'))
        raise RuntimeError(f'Error executing command: {args}')
    try:
        res = proc.stdout.decode(errors='replace')
    except Exception as e:
        print(f'Exception occured while trying to decode process output for commmand: {args}')
        raise RuntimeError(e)
    return res

def remote_execute(cmd: str|list[str], verbose=False) -> str:
    #wrap cmd first in a zsh login call to ensure access to all normal executables
    #then wrap that in a ssh call to the remote host
    if isinstance(cmd, list):
        cmd = shlex.join(cmd)
    full_cmd = f"ssh {remote_host} 'zsh -lc \"{cmd}\"'"
    if verbose:
        print(f'Remote executing full_cmd: {full_cmd}')
    args = shlex.split(full_cmd)
    return run_process(args)


def ensure_remote_directory(path: str):
    path = normalize_path(path)
    if_action = f"echo 'true'"
    else_action = f'mkdir -p {path}'
    if_cmd = f'''if [ -d {path} ]; then {if_action}; else {else_action}; fi'''
    res_str = remote_execute(if_cmd).rstrip()
    if res_str == 'true':
        return True
    # print(res_str, end='')









